# Generated by Django 5.0.2 on 2024-08-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_importer.criteria')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_importer.phase'),
        ),
        migrations.CreateModel(
            name='ScoreRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_min', models.IntegerField()),
                ('range_max', models.IntegerField()),
                ('performance_level', models.CharField(max_length=50)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_importer.criteria')),
            ],
        ),
    ]
