# Generated by Django 5.0.2 on 2024-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('criteria_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='scorerange',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='co_code',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='max_score',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='ScoreRange',
        ),
    ]
