# Generated by Django 5.0.2 on 2024-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0002_phase1_remove_criteria_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('criteria_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('criteria_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('criteria_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('criteria_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
