# Generated by Django 5.0.2 on 2024-08-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0003_phase2_phase3_phase4_phase5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria1',
            fields=[
                ('phase_number', models.IntegerField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
