# Generated by Django 5.0.2 on 2024-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0004_criteria1_delete_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria1',
            name='criteria_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criteria1',
            name='phase_number',
            field=models.IntegerField(),
        ),
    ]
