# Generated by Django 5.0.2 on 2024-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0005_criteria1_criteria_id_alter_criteria1_phase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria1',
            name='criteria_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
